### PR TITLE
Redesigned for Semantic UI 2 and removed LESS dependency.

### LINKED ISSUE #20: Please remove less package dependency
This [less-autoprefixer package](https://github.com/flemay/less-autoprefixer/) by @flemay and handles auto prefix and is therefore a lot more useful than the standard `less` package. Unfortunately, `useraccounts:semantic-ui` **requires** the `less` package, which is incompatible with `less-autoprefixer`.

Here's what the console shows:

```
=> Errors prevented startup:                  
   
   While building the application:
   error: conflict: two packages included in resources, flemay:less-autoprefixer and less,
   are both trying to handle .less
   error: conflict: two packages included in resources, flemay:less-autoprefixer and less,
   are both trying to handle .import.less
```

EDIT: by the way, I think the official `semantic-ui` meteor package dropped the `less` package dependency and recommends to use `flemay:less-autoprefixer`

### LINKED ISSUE #21: Do we need a version of this for Semantic UI 2.0?
I am not sure what we are missing by not having it at SUI 2.0. Anyway, I have this installed and it seems to work okay so far with my Semantic UI 2.0 setup. Thoughts? Thanks for useraccounts! Very awesome set of packages that the Meteor community now depends on frequently.

### PR DESCRIPTION
**Pull request by lumatijev**
Some non breaking changes to match Semantic UI 2 design style. This closes #21.

Removed LESS package dependency. This closes #20.

Didn't drop large class for now. Will do it later if we all agree about that. References #19.

### CODE REVIEW

File: package.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 Package.describe({
   summary: 'Accounts Templates styled for Semantic UI.',
-  version: '1.11.1',
+  version: '1.12.0',
```
Comment (splendido) [inline package.js]: Could you please revert back to 1.11.1?
I have some scripts that will automatically bump at the next publish operation...

Comment (lumatijev) [inline package.js]: Sure. Will be done in an hour.

**Comment by splendido** [comment]
Lets try it out a little bit!
...I'll see when I can have a look at it
